title: NerdyNikoleta
email: nerdynick@gmail.com
description: >-
  My personal DevOps, Engineering, & Architecture related Examples and Writings.
  Covering things related to Security, Platform Engineering, Confluent, and Apache Kafka.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://coding.nerdynick.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: NerdyNikoleta
github_username:  nerdynick

# Build settings
remote_theme: jekyll/minima
# theme: minima
plugins:
  # - jekyll-remote-theme
  - jekyll-feed
  - jekyll-gist

minima:
  skin: solarized-dark
show_excerpts: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
